tech_child = {
    # --- Core Languages ---
    "JavaScript": [],
    "TypeScript": [],
    "Java": [],
    "Kotlin": ["Java"],
    "Python": [],
    "R": [],
    "Swift": ["iOS Development"],
    "Dart": ["Flutter"],

    # --- Frontend Frameworks ---
    "React": ["JavaScript"],
    "Vue.js": ["JavaScript"],
    "Next.js": ["React", "JavaScript"],
    "Nuxt.js": ["Vue.js", "JavaScript"],
    "Tailwind": ["CSS3"],
    "Vite": ["JavaScript"],
    "Webpack": ["JavaScript"],
    "Storybook": ["JavaScript", "UI/UX"],

    # --- Backend / APIs ---
    "Node.js": ["JavaScript"],
    "Express.js": ["Node.js", "JavaScript"],
    "Spring Boot": ["Java"],
    "FastAPI": ["Python"],
    "Flask": ["Python"],
    "Django": ["Python"],
    "REST API": ["Backend Development"],

    # --- Databases ---
    "MySQL": ["Database Technologies"],
    "PostgreSQL": ["Database Technologies"],
    "Oracle": ["Database Technologies"],
    "MongoDB": ["NoSQL", "Database Technologies"],
    "NoSQL": ["Database Technologies"],
    "SQL Scripting": ["Database Technologies"],
    "Database Design": ["Database Development"],
    "Database Management": ["Database Development"],
    "Database Development": ["Database Technologies"],

    # --- Cloud Providers ---
    "AWS": [],
    "Azure": [],
    "GCP": [],
    "AWS CLI": ["AWS"],
    "Azure CLI": ["Azure"],
    "CloudFormation": ["AWS"],
    "Vertex AI": ["GCP", "MLOps"],

    # --- Infra as Code / Config ---
    "Terraform": ["Infrastructure as Code"],
    "Ansible": ["Configuration Management"],
    "Puppet": ["Configuration Management"],
    "Chef": ["Configuration Management"],

    # --- Containers / Orchestration ---
    "Docker": ["DevOps"],
    "Kubernetes": ["DevOps"],

    # --- MLOps / Distributed ---
    "Weights & Biases": ["MLOps"],
    "MLflow": ["MLOps"],
    "TorchServe": ["PyTorch", "MLOps"],
    "BentoML": ["MLOps"],
    "Seldon": ["MLOps"],
    "Ray": ["Distributed Training"],

    # --- Networking ---
    "DHCP": ["Network Management"],
    "DNS": ["Network Management"],
    "Routing Protocols": ["Networking"],
    "TCP/IP": ["Networking"],
    "LAN Technology": ["Networking"],
    "WAN Load Balancers": ["Networking"],
    "Proxy Servers": ["Networking"],
    "VPN": ["Networking"],
    "Subnetting": ["Networking"],
    "VLANs": ["Networking"],
    "Wireless Network": ["Networking"],
    "Wired Network": ["Networking"],

    # --- Storage ---
    "Storage": [],
    "NAS Storage": ["Storage"],
    "SAN": ["Storage"],
    "EMC Storage": ["Storage"],
    "Storage & Backup": ["Storage"],
    "Backup Software": ["Backup/Restore"],

    # --- Reporting / Visualization ---
    "Crystal Report": ["Reporting"],
    "Fast Report": ["Reporting"],

    # --- Data Engineering ---
    "Data Collection": ["Data Management"],
    "Data Cleaning": ["Data Management"],
    "Data Validation": ["Data Management"],
    "Data Transfer": ["Data Management"],
    "Data Analysis": ["Data Management"],
    "Data Governance": ["Data Management"],
    "Data Management": [],
    "Data Engineering": ["Data Management"],
    "Database Technologies": ["Data Management"],
    "ETL": ["Data Engineering"],
    "Talend": ["ETL"],
    "Informatica": ["ETL"],
    "Apache NiFi": ["ETL"],
    "Snowflake": ["Database Technologies", "Cloud"],
    "Redshift": ["Database Technologies", "Cloud"],
    "BigQuery": ["Database Technologies", "Cloud"],
    "Delta Lake": ["Data Engineering"],
    "Apache Kafka": ["Data Engineering"],
    "Spark Streaming": ["Apache Kafka", "Data Engineering"],
    "Flink": ["Data Engineering"],
    "Airflow": ["Data Engineering"],
    "Prefect": ["Data Engineering"],
    "Dagster": ["Data Engineering"],

    # --- Data Visualization / Reporting ---
    "Dashboard Design": ["Data Visualization"],
    "Data Visualization": ["Data Management"],
    "Reporting": ["Data Visualization"],
    "Report Generation": ["Reporting"],
    "Report Tools": ["Reporting"],
    "PowerBI": ["Data Visualization"],
    "Tableau": ["Data Visualization"],
    "Qlik Sense": ["Data Visualization"],
    "Crystal Report": ["Reporting"],
    "Fast Report": ["Reporting"],
    "Looker": ["Data Visualization"],
    "Metabase": ["Data Visualization"],
    "Superset": ["Data Visualization"],

    # --- Machine Learning / AI ---
    "Machine Learning": ["Data Analysis"],
    "Deep Learning": ["Machine Learning"],
    "NLP": ["Machine Learning"],
    "LLMs": ["Machine Learning"],
    "Generative AI": ["LLMs"],
    "Prompt Engineering": ["LLMs"],
    "RAG": ["LLMs"],
    "scikit-learn": ["Python", "Machine Learning"],
    "PyTorch": ["Python", "Machine Learning"],
    "TensorFlow": ["Python", "Machine Learning"],
    "Keras": ["Python", "Deep Learning"],
    "Transformers": ["Deep Learning", "NLP"],
    "Detectron2": ["PyTorch", "Computer Vision"],
    "YOLO": ["Computer Vision", "Deep Learning"],
    "MediaPipe": ["Computer Vision"],
    "Prophet": ["Time Series Analysis"],
    "ARIMA": ["Time Series Analysis"],
    "tsfresh": ["Time Series Analysis"],
    "sktime": ["Time Series Analysis"],
    "Surprise": ["Recommender Systems"],
    "implicit": ["Recommender Systems"],

    # --- Computer Vision / Image Processing ---
    "OpenCV": ["Computer Vision", "Python"],
    "Pillow": ["Image Processing", "Python"],
    "scikit-image": ["Image Processing", "Python"],
    "Image Processing": ["Computer Vision"],
    "Computer Vision": ["Machine Learning"],

     # --- Security ---
    "Cybersecurity": [],
    "Firewall": ["Cybersecurity"],
    "Firewall Management": ["Firewall"],
    "Endpoint Security": ["Cybersecurity"],
    "Authentication Patterns": ["Cybersecurity"],
    "IAM": ["Cybersecurity"],
    "MFA": ["IAM"],

    # --- Networking ---
    "IP Addressing": ["Networking"],
    "IPS": ["Cybersecurity"],

    # --- Testing / QA ---
    "Software Testing": ["Software Development"],
    "Functional Testing": ["Software Testing"],
    "Regression Testing": ["Software Testing"],
    "Manual Testing": ["Software Testing"],
    "Quality Assurance": ["Software Testing"],
    "Quality Control": ["Software Testing"],
    "Testing Library": ["Software Testing"],
    "System Integration Testing (SIT)": ["Software Testing"],

    # --- Software / Development Methodology ---
    "OOP": [],
    "Agile": [],
    "Scrum": ["Agile"],
    "Kanban": ["Agile"],
    "Extreme Programming (XP)": ["Agile"],
    "Lean Software Development": ["Agile"],
    "Waterfall": [],
    "V-Model": [],
    "Spiral Model": [],
    "Feature-Driven Development (FDD)": ["Agile"],
    "System Design": [],
    "Solution Design": [],

    # --- Office / Productivity Tools ---
    "Microsoft Office": [],
    "Microsoft Word": ["Microsoft Office"],
    "Excel": ["Microsoft Office"],
    "PowerPoint": ["Microsoft Office"],
    "O365": ["Microsoft 365 Administration"],
    "Microsoft 365 Administration": [],
    "Ticketing Systems": ["IT Service Delivery"],
    "Help Desk Support": ["IT Service Delivery"],

    # --- Miscellaneous / Admin / Infra ---
    "IT Infrastructure": [],
    "IT Operations": ["IT Infrastructure"],
    "IT Service Delivery": ["IT Operations"],
    "Cloud IT Architecture Design": ["Cloud Engineering"],
    "Infrastructure as Code": ["IT Infrastructure"],
    "Configuration Management": ["IT Infrastructure"],
    "Server Administration": ["IT Infrastructure"],
    "Linux Server Administration": ["Linux"],
    "Windows Server": ["Windows"],
    "Windows": [],
    "Linux": [],
    "Red Hat Enterprise Linux": ["Linux"],
}
