tech_skills_child = {
    # Programming Languages
    "TypeScript": [],
    "JavaScript": [],
    "Java":[],
    "Kotlin": ["Flutter"],
    "Swift": ["Flutter"],
    "Dart": [],
    "PHP": [],
    "C#": [],
    "Ruby": [],
    "Golang": [],
    "Rust": [],
    "Python": [],
    "R": [],

    # Frontend Frameworks
    "React": ["JavaScript"],
    "Vue.js": ["JavaScript"],
    "Next.js": ["React", "JavaScript"],
    "Nuxt.js": ["Vue.js", "JavaScript"],
    "Tailwind": [],
    "Vite": ["JavaScript"],
    "Webpack": ["JavaScript"],
    "Storybook": ["React", "Vue.js"],

    # Backend / Web Frameworks
    "Node.js": ["JavaScript"],
    "Express.js": ["JavaScript"],
    "Spring Boot": ["Java"],
    "FastAPI": ["Python"],
    "Flask": ["Python"],
    "Django": ["Python"],
    "REST API": ["Backend Development"],
    "REST":[],

    # Databases
    "MySQL": [],
    "PostgreSQL": [],
    "Oracle": [],
    "MongoDB": [],
    "NoSQL": [],
    "SQL": [],

    # Cloud
    "AWS CLI": [],
    "Azure CLI": [],
    "CloudFormation": [],
    "Vertex AI": ["GCP", "Machine Learning"],
    "Terraform": ["Cloud IT Architecture Design", "Infrastructure as Code"],
    "Ansible": ["Configuration Management"],
    "Puppet": ["Configuration Management"],
    "Chef": ["Configuration Management"],
    "Docker": ["Containerization"],
    "Kubernetes": ["Containerization", "Orchestration"],
    "Weights & Biases": ["Machine Learning"],
    "MLflow": ["Machine Learning"],
    "TorchServe": ["PyTorch"],
    "BentoML": ["Machine Learning"],
    "Seldon": ["Machine Learning"],
    "Ray": ["Machine Learning"],

    # Networking / Security
    "VPN": ["Network Security"],
    "Proxy Servers": ["Network Security"],
    "Wireless Network": ["Network"],
    "Wired Network": ["Network"],
    "NAS Storage": ["Storage & Backup"],
    "SAN": ["Storage & Backup"],
    "EMC Storage": ["Storage & Backup"],
    "Storage & Backup": [],
    "Firewall": ["Network Security"],
    "Firewall Management": ["Firewall"],
    "Endpoint Security": ["Cybersecurity"],
    "IAM": ["Cybersecurity"],
    "MFA": ["Cybersecurity"],
    "Encryption": ["Cybersecurity"],
    "Penetration Testing": ["Cybersecurity"],
    "Incident Response": ["Cybersecurity"],
    "Network Security": ["Network"],

    # Machine Learning / AI
    "Machine Learning": ["Python"],
    "Deep Learning": ["Machine Learning", "Python"],
    "NLP": ["Deep Learning"],
    "Computer Vision": ["Deep Learning", "Image Processing"],
    "Image Processing": ["Python"],
    "LLMs": ["NLP"],
    "Generative AI": ["Deep Learning", "LLMs"],
    "RAG": ["Generative AI"],
    "Prompt Engineering": ["Generative AI"],
    "scikit-learn": ["Machine Learning", "Python"],
    "PyTorch": ["Machine Learning", "Python"],
    "TensorFlow": ["Machine Learning", "Python"],
    "Keras": ["TensorFlow"],
    "Transformers": ["NLP", "PyTorch"],
    "Detectron2": ["Computer Vision", "PyTorch"],
    "YOLO": ["Computer Vision", "PyTorch"],
    "MediaPipe": ["Computer Vision", "Python"],
    "OpenCV": ["Computer Vision", "Python"],
    "Pillow": ["Image Processing", "Python"],
    "scikit-image": ["Image Processing", "Python"],
    "Time Series Analysis": ["Machine Learning", "Python"],
    "Prophet": ["Time Series Analysis"],
    "ARIMA": ["Time Series Analysis"],
    "tsfresh": ["Time Series Analysis"],
    "sktime": ["Time Series Analysis"],
    "Recommender Systems": ["Machine Learning", "Python"],
    "Surprise": ["Recommender Systems"],
    "implicit": ["Recommender Systems"],
    "Reinforcement Learning": ["Machine Learning", "Python"],

    # Data / BI
    "Data Cleaning": ["Python", "Excel"],
    "Data Wrangling": ["Python", "Excel"],
    "Big Data Technologies": ["Python", "SQL"],
    "Tableau": ["Business Intelligence (BI)"],
    "PowerBI": ["Business Intelligence (BI)"],
    "Qlik Sense": ["Business Intelligence (BI)"],
    "Excel": [],
    "Crystal Report": ["Report Tools"],
    "Fast Report": ["Report Tools"],
    "Looker": ["Business Intelligence (BI)"],
    "Metabase": ["Business Intelligence (BI)"],
    "Superset": ["Business Intelligence (BI)"],
    "Talend": ["ETL"],
    "Informatica": ["ETL"],
    "Apache NiFi": ["ETL"],

    # Testing / QA
    "Software Testing": [],
    "Functional Testing": ["Software Testing"],
    "Regression Testing": ["Software Testing"],
    "Manual Testing": ["Software Testing"],
    "Quality Assurance": ["Software Testing"],
    "Quality Control": ["Software Testing"],
    "Testing Library": ["Software Testing"],
    "Unit Testing": ["Software Testing"],
    "Integration Testing": ["Software Testing"],
    "Performance Testing": ["Software Testing"],
    "Test Automation": ["Software Testing"],
    "Test-Driven Development (TDD)": ["Software Testing"],

    # DevOps / CI-CD
    "CI/CD": [],
    "Jenkins": ["CI/CD"],
    "GitLab CI": ["CI/CD"],
    "Helm": ["Kubernetes"],
    "Kubernetes Operators": ["Kubernetes"],

    # Methodologies / PM
    "Agile": [],
    "Scrum": ["Agile"],
    "Kanban": ["Agile"],
    "Extreme Programming (XP)": ["Agile"],
    "Lean Software Development": ["Agile"],
    "Waterfall": [],
    "V-Model": [],
    "Spiral Model": [],
    "OOP": ["Programming Fundamentals"],
    "Feature-Driven Development (FDD)": ["OOP"],
    "System Design": ["Programming Fundamentals"],
    "Solution Design": ["System Design"],
    "Project Management": [],
    "Problem-Solving": [],
    "Analytical Thinking": [],
    "Communication": [],
    "Adaptability": [],
    "Collaboration": [],

    # Office / Tools
    "Microsoft Word": ["Microsoft Office"],
    "PowerPoint": ["Microsoft Office"],
    "O365": ["Microsoft Office"],
    "Microsoft 365 Administration": ["O365"],
    "Dashboard Design": ["Data Visualization"],
    "Data Visualization": ["Business Intelligence (BI)"],
    "Reporting": ["Data Visualization"],
    "Report Generation": ["Reporting"],
    "Report Tools": [],
    
    # OS / Servers
    "Linux": [],
    "Windows": [],
    "Windows Server": ["Windows"],
    "Red Hat Enterprise Linux": ["Linux"],
    "Linux Server Administration": ["Linux"],

    # Mobile / Cross-platform
    "iOS Development": ["Swift"],
    "Flutter": [],

    # Cloud / Infra
    "Snowflake": ["Big Data Technologies"],
    "Redshift": ["Big Data Technologies"],
    "BigQuery": ["Big Data Technologies"],
    "Delta Lake": ["Big Data Technologies"],
    "Apache Kafka": ["Big Data Technologies"],
    "Spark Streaming": ["Big Data Technologies"],
    "Flink": ["Big Data Technologies"],
    "Airflow": ["ETL"],
    "Prefect": ["ETL"],
    "Dagster": ["ETL"],
    "Cloud IT Architecture Design": ["Cloud Architecture"],
    "Infrastructure as Code": ["Cloud IT Architecture Design"],
    "Configuration Management": [],
    "Server Administration": [],
    "IT Infrastructure": [],
    "IT Operations": ["IT Infrastructure"],
    "IT Service Delivery": ["IT Infrastructure"],
    "Cloud Architecture": [],
    "Serverless Computing": ["Cloud Architecture"],
    "Multicloud Environments": ["Cloud Architecture"],
    "Compliance (GDPR, CCPA)": ["Cybersecurity"],

    # Network
    "Network" : [],
    "DHCP": ["Network"],
    "DNS": ["Network"],
    "Routing Protocols": ["Network"],
    "TCP/IP": ["Network"],
    "LAN Technology": ["Network"],
    "WAN Load Balancers": ["Network"],
    "IP Addressing": ["Network"],
    "IPS": ["Network Security"],
    "Network Monitoring Tools": ["Network"],

    # Additional Skills
    "OOP": [],
    "System Design": [],
}
