Tech_skills = {
    # Programming Languages
    "Python": ["Scripting"],
    "JavaScript": ["Scripting"],
    "TypeScript": ["JavaScript","Scripting"],
    "Java": ["Scripting"],
    "Golang": ["Scripting"],
    "R": ["Scripting"],
    "SQL": ["Scripting"],
    "NoSQL": ["Scripting"],
    "HTML5": ["Scripting"],
    "CSS3": ["HTML5"],
    "Bash Scripting": ["Linux"],
    "PowerShell": ["Windows Server"],
    "VBS": ["Windows Server"],
    "Dart": ["Scripting"],
    "Kotlin": ["Scripting"],
    "Swift": ["Scripting"],

    # Programming Concepts
    "OOP": ["Programming"],

    "Git": [],
    "REST API": ["Node.js", "Express.js", "FastAPI", "Spring Boot"],

    # Frontend
    "React": ["JavaScript","Tailwind"],
    "Next.js": ["React","TypeScript"],
    "Vue.js": ["JavaScript"],           
    "Nuxt.js": ["Vue.js"],              
    "Vite": ["JavaScript"],
    "Webpack": ["JavaScript"],
    "Tailwind": ["CSS3"],
    "UI/UX": [],
    "Figma": ["UI/UX"],
    "Accessibility": ["UI/UX"],
    "Frontend Development": ["JavaScript","CSS3"],
    "Flutter": ["Dart"],

    # Backend
    "Node.js": ["JavaScript"],
    "Express.js": ["Node.js"],
    "FastAPI": ["Python"],
    "Spring Boot": ["Java"],
    "Backend Development": [],

    # Native Platforms
    "Android Development": ["Flutter","Kotlin","Java"],
    "iOS Development": ["Flutter","Swift"],

    # Full Stack
    "Full Stack Development": ["Frontend Development", "Backend Development"],

    # Testing / QA
    "Testing": [],
    "Jest": ["Testing","JavaScript"],
    "Testing Library": ["Testing","JavaScript"],
    "Storybook": ["Testing","JavaScript"],
    "Quality Assurance": ["Testing"],
    "Quality Control": ["Testing"],
    "Functional Testing": ["Testing"],
    "Regression Testing": ["Testing"],
    "System Integration Testing (SIT)": ["Testing"],
    "Manual Testing": ["Testing"],

    # Data / AI / ML
    "Artificial Intelligence": [],
    "Generative AI": ["Artificial Intelligence"],
    "Machine Learning": ["Python","Artificial Intelligence"],
    "Deep Learning": ["Machine Learning","Python"],
    "scikit-learn": ["Machine Learning","Python"],
    "TensorFlow": ["Deep Learning","Python"],
    "PyTorch": ["Deep Learning","Python"],
    "CUDA": ["Deep Learning"],
    "Transformers": ["Deep Learning","NLP"],
    "NLP": ["Machine Learning"],
    "Representation Learning": ["Machine Learning"],
    "Distributed Training": ["Deep Learning"],
    "MLOps": ["Machine Learning","Python"],
    "Ray": ["Distributed Training","Python"],
    "Vertex AI": ["MLOps","GCP"],
    "Weights & Biases": ["MLOps","Deep Learning"],
    "LLMs": ["Deep Learning","NLP"],
    "vLLM": ["LLMs"],
    "RAG": ["LLMs","Retrieval"],
    "Retrieval": ["NLP"],
    "Multimodal": ["Deep Learning","LLMs"],
    "AI Systems": ["Machine Learning"],
    "Prompt Engineering": ["LLMs"],
    "Paper Writing": ["AI Systems"],
    "Optimization": ["Machine Learning"],

    # Data Engineering
    "Data Engineering": ["Python","SQL"],
    "Data Analysis": ["Python","SQL"],
    "Data Cleaning": ["Data Analysis"],
    "Data Collection": ["Data Analysis"],
    "Data Validation": ["Data Analysis"],
    "Data Governance": ["Data Management"],
    "Data Management": ["SQL"],
    "Data Protection": ["Cybersecurity"],
    "Data Security": ["Cybersecurity"],
    "Data Transfer": ["Networking"],
    "Data Visualization": ["Python"],
    "PowerBI": ["Data Visualization"],
    "Tableau": ["Data Visualization"],
    "Qlik Sense": ["Data Visualization"],
    "SAS": ["Statistical Analysis"],
    "SPSS": ["Statistical Analysis"],
    "Crystal Report": ["Reporting"],
    "Fast Report": ["Reporting"],

    # Databases
    "MySQL": ["SQL"],
    "PostgreSQL": ["SQL"],
    "Oracle": ["SQL"],
    "MongoDB": ["NoSQL"],
    "Database Design": ["SQL"],
    "Database Development": ["SQL"],
    "Database Management": ["SQL"],
    "Database Technologies": ["SQL"],

    # Reporting / BI
    "Business Intelligence": ["Data Analysis"],
    "Dashboard Design": ["Data Visualization"],
    "Report Generation": ["Reporting"],
    "Report Tools": ["Reporting"],
    "Reporting": [],

    # Cloud
    "Cloud": [],
    "AWS": ["Cloud"],
    "Azure": ["Cloud"],
    "GCP": ["Cloud"],
    "AWS CLI": ["AWS"],
    "Azure CLI": ["Azure"],
    "Cloud Engineering": ["Cloud"],
    "Cloud IT Architecture Design": ["Cloud"],
    "Cloud Services": ["Cloud"],
    "CloudFormation": ["AWS"],

    # Infra / DevOps
    "Docker": ["CI/CD"],
    "Kubernetes": ["CI/CD","Docker"],
    "CI/CD": [],
    "Ansible": ["Configuration Management"],
    "Chef": ["Configuration Management"],
    "Puppet": ["Configuration Management"],
    "Terraform": ["Configuration Management"],
    "Configuration Management": [],
    "Microservices": ["Docker","Kubernetes"],
    "Infrastructure as Code": ["DevOps"],
    "DevOps": [],

    # Networking
    "Networking": [],
    "LAN Technology": ["Networking"],
    "TCP/IP": ["Networking"],
    "DNS": ["Networking"],
    "DHCP": ["Networking"],
    "Routing Protocols": ["Networking"],
    "Subnetting": ["Networking"],
    "Proxy Servers": ["Networking"],
    "VPN": ["Networking"],
    "VLANs": ["Networking"],
    "WAN Load Balancers": ["Networking"],
    "Wired Network": ["Networking"],
    "Wireless Network": ["Networking"],
    "Traffic Shaping": ["Networking"],
    "Bandwidth Management": ["Networking"],
    "IP Addressing": ["Networking"],
    "Network Troubleshooting": ["Networking"],
    "Network Management": ["Networking"],
    "Network Infrastructure Maintenance": ["Networking"],

    # Security
    "Cybersecurity": [],
    "Firewall": ["Cybersecurity"],
    "Firewall Management": ["Cybersecurity"],
    "Antivirus": ["Cybersecurity"],
    "Endpoint Security": ["Cybersecurity"],
    "Security & Compliance": ["Cybersecurity"],
    "Authentication Patterns": ["Cybersecurity"],
    "IPS": ["Cybersecurity"],
    "MFA": ["Cybersecurity"],
    "IAM": ["Cybersecurity"],

    # System / IT Infra
    "Windows Server": [],
    "Windows Clustering": ["Windows Server"],
    "Linux": [],
    "Red Hat Enterprise Linux": ["Linux"],
    "Linux System": ["Linux"],
    "Linux Server Administration": ["Linux"],
    "Server Administration": [],
    "Hardware": [],
    "Hardware Maintenance": ["Hardware"],
    "Device Driver Installation": ["Hardware"],
    "Virtualization": ["IT Infrastructure"],
    "VMware": ["Virtualization"],
    "NAS Storage": ["Storage"],
    "SAN": ["Storage"],
    "EMC Storage": ["Storage"],
    "Storage & Backup": ["Storage"],
    "Backup Software": ["Storage & Backup"],
    "Backup/Restore": ["Storage & Backup"],
    "IT Infrastructure": [],
    "IT Operations": ["IT Infrastructure"],
    "IT Service Delivery": ["IT Infrastructure"],

    # Business / ERP / CRM
    "ERP Systems": [],
    "ERP/Accounting Software": ["ERP Systems"],
    "Business Applications": [],
    "CRM/POS": ["Business Applications"],
    "Client Relationship Management": ["Business Applications"],
    "Customer Management": ["Business Applications"],

    # Office / Tools
    "Microsoft 365 Administration": [],
    "O365": ["Microsoft 365 Administration"],
    "Microsoft Office": [],
    "Microsoft Word": ["Microsoft Office"],
    "PowerPoint":["Microsoft Office"],
    "Excel": ["Microsoft Office"],
    "Office Applications": ["Microsoft Office"],
    "Web Application Development": ["Software Development"],
    "Window Application Development": ["Software Development"],
    "Software Development": [],

    # Other Technical
    "Scripting": ["Programming"],
    "Programming": [],
    "Debugging": ["Programming"],
    "System Design": [],
    "Solution Design": ["System Design"],
    "Software Systems": ["System Design"],
    "Software Installation": [],
    "Software Testing": ["Testing"],
    "Software Troubleshooting": ["Technical Support"],
    "Technical Documentation": ["Documentation"],
    "Documentation": [],
    "Functional Documentation": ["Documentation"],
    "Technical Support": [],
    "Remote Support": ["Technical Support"],
    "Help Desk Support": ["Technical Support"],
    "Ticketing Systems": ["Technical Support"],
    "Video Conferencing": [],

    # Development Methodologies
    "Agile": [],
    "Scrum": ["Agile"],
    "Kanban": ["Agile"],
    "Extreme Programming (XP)": ["Agile"],
    "Feature-Driven Development (FDD)": ["Agile"],
    "Lean Software Development": ["Agile"],
    "Waterfall": [],
    "V-Model": [],
    "Spiral Model": [],
    "DevOps": ["Agile"],
}

Accounting_finance_skills = {
    # Core Accounting
    "Accounting": [],
    "GAAP": ["Accounting"],
    "IFRS": ["Accounting"],
    "Tax": ["Accounting"],
    "Tax Compliance": ["Tax", "Accounting"],
    "Tax Filing": ["Tax Compliance"],
    "Tax Return": ["Tax Compliance"],
    "Tax Reconciliation": ["Tax Compliance"],
    "Tax Reporting": ["Tax Compliance"],
    "Withholding Taxes": ["Tax"],
    "WHT Certificates": ["Tax"],
    "VAT": ["Tax"],
    "VAT/GL Reporting": ["Tax", "General Ledger"],
    "Audit Support": ["Accounting"],
    "Internal Audit": ["Accounting"],
    "Internal Controls": ["Accounting"],
    "Reconciliations": ["Accounting"],
    "Bank Reconciliation": ["Reconciliations"],
    "Sales Reconciliation": ["Reconciliations"],
    "Consolidations": ["Accounting"],
    "Cost Control": ["Accounting"],
    "Cost Analysis": ["Accounting"],

    # Accounts
    "Accounts Payable": ["Accounting"],
    "Accounts Receivable": ["Accounting"],
    "Accounts Receivable Management": ["Accounts Receivable"],
    "Debt Collection": ["Accounts Receivable"],
    "Billing": ["Accounts Receivable"],
    "Invoice Issuing": ["Accounts Receivable"],
    "Invoice Preparation": ["Accounts Receivable"],
    "Commission Invoice Review and Approval": ["Accounts Receivable"],
    "Payment Processing": ["Accounts Payable"],
    "Payment Recording": ["Accounts Payable"],
    "Expense Verification": ["Accounts Payable"],

    # Financial Reporting
    "Financial Management": ["Finance"],
    "Financial Planning & Analysis": ["Finance"],
    "Financial Planning": ["Financial Planning & Analysis"],
    "Financial Reporting": ["Finance"],
    "Financial Statements": ["Financial Reporting"],
    "Financial Statement Preparation": ["Financial Reporting"],
    "Statutory Filings": ["Financial Reporting"],
    "Forecasting": ["Finance"],
    "Cash Flow Management": ["Finance"],
    "Budgeting": ["Finance"],
    "Budget Monitoring": ["Budgeting"],
    "Variance Analysis": ["Financial Reporting"],
    "Excel Modeling": ["Financial Reporting"],

    # Finance (existing relations)
    "Finance": [],
    "Corporate Finance": ["Finance"],
    "M&A": ["Corporate Finance"],
    "Financial Modeling": ["Finance"],
    "Equity Research": ["Finance"],
    "Valuation": ["Finance"],
    "Risk Management": ["Finance"],
    "Risk Analysis": ["Risk Management"],
    "Risk Models": ["Risk Management"],
    "Portfolio Management": ["Finance"],
    "Portfolio Construction": ["Portfolio Management"],
    "Investment Strategies": ["Finance"],
    "Pitchbooks": ["Corporate Finance"],
    "FactSet": ["Finance"],
    "Capital IQ": ["Finance"],
    "Bloomberg Terminal": ["Finance"],
    "Bloomberg": ["Finance"],

    # Ledgers & Transactions
    "General Ledger": ["Accounting"],
    "General Ledger Management": ["General Ledger"],
    "Journal Entries": ["General Ledger"],
    "Transaction Processing": ["Accounting"],
    "Financial Transactions": ["Accounting"],
    "Vouchers": ["Accounting"],
    "Sales Recording": ["Accounting"],
    "Sales Summary": ["Accounting"],

    # Payroll & HR
    "Payroll Management": ["Accounting"],
    "Compensation and Benefits Administration": ["Payroll Management"],
    "HR Operations": [],

    # Assets
    "Fixed Assets": ["Accounting"],
    "Depreciation": ["Fixed Assets"],
    "Asset Tracking": ["Fixed Assets"],
    "Inventory Management": ["Accounting"],
    "Inventory Tracking": ["Inventory Management"],

    # ERP / Tools
    "ERP Systems": ["Accounting"],
    "SAP": ["ERP Systems"],
    "Navision": ["ERP Systems"],
    "PEAK Accounting Software": ["Accounting"],
    "QuickBooks": ["Accounting Software"],
    "Accounting Software": ["Accounting"],
    "Bookkeeping": ["Accounting"],
    "Microsoft Office": [],
    "MS Office": ["Microsoft Office"],
    "MS Office Suite": ["Microsoft Office"],
    "MS Office (Excel, PowerPoint)": ["Microsoft Office"],
    "Microsoft Office Suite (Excel, Word, PowerPoint)": ["Microsoft Office"],
    "Office Automation Tools": ["Microsoft Office"],
    "Excel Modeling": ["Microsoft Office"],
    "Power BI": ["BI Reporting"],
    "Tableau": ["BI Reporting"],
    "Visualization Dashboards": ["BI Reporting"],
    "BI Reporting": ["Finance"],

    # Compliance & Regulatory
    "Compliance": ["Accounting"],
    "Regulatory Compliance": ["Compliance"],
    "Sanctions Program Audit": ["Compliance"],
    "Corporate Documents": ["Compliance"],
    "Contract Management": ["Compliance"],

    # Reporting
    "Reporting": ["Finance"],
    "Report Preparation": ["Reporting"],
    "Reporting Standards": ["Reporting"],

    # Automation & Data
    "Data Entry": ["Accounting"],
    "Data Organization": ["Data Entry"],
    "Data Governance": ["Accounting"],
    "Data Quality Assurance": ["Accounting"],
    "RPA": ["Automation"],
    "Automation": [],

    # Business / Administration
    "Business Administration": [],
    "Business Process Mapping": ["Business Administration"],
    "Organisation": ["Business Administration"],
    "Organization": ["Business Administration"],
    "Admin Tasks": ["Business Administration"],
    "Administrative Support": ["Business Administration"],

    # Vendors
    "Vendor Management": ["Finance"],
    "Purchasing": ["Vendor Management"],
}

Design_skills = {
    # Core Design
    "Design": [],
    "2D Design": ["Design"],
    "3D Design": ["Design"],
    "Product Design": ["Design"],
    "Creative Design": ["Design"],
    "Branding Design": ["Design"],
    "Graphic Design": ["Design"],
    "UI Design": ["Design"],
    "UX Design": ["Design"],

    # Tools / Software
    "Adobe Creative Cloud": [],
    "Adobe Photoshop": ["Adobe Creative Cloud"],
    "Adobe Illustrator": ["Adobe Creative Cloud"],
    "Adobe InDesign": ["Adobe Creative Cloud"],
    "Adobe XD": ["Adobe Creative Cloud"],
    "Adobe After Effects": ["Adobe Creative Cloud"],
    "Adobe Premiere Pro": ["Adobe Creative Cloud"],
    "Lightroom": ["Adobe Creative Cloud"],
    "Canva": [],
    "Figma": [],
    "Sketch": [],
    "AutoCAD": [],
    "3D SketchUp": ["3D Design"],
    "Autodesk 3ds Max": ["3D Design"],
    "Autodesk Maya": ["3D Design"],
    "Blender": ["3D Design"],
    "Cinema 4D": ["3D Design"],
    "Solidworks": ["3D Design"],
    "NX": ["3D Design"],
    "MS Office": [],
    "Power BI": [],  # อันนี้โยงกับ BI/reporting จากบัญชีได้ด้วย

    # Visualization / Prototyping
    "3D Visualization": ["3D Design"],
    "Wireframing": ["UI Design"],
    "Prototyping": ["UI Design"],
    "Mockups": ["UI Design"],
    "Storyboarding": [],
    "Motion Graphics": ["After Effects"],
    "Video Editing": ["Adobe Premiere Pro"],
    "Image Retouching": ["Photoshop"],
    "Clipping Paths": ["Photoshop"],

    # Architecture / Construction
    "Architectural Design Review": ["Design"],
    "Construction Detailing": ["Architectural Design Review"],
    "Joinery": ["Architectural Design Review"],
    "Space Planning": ["Architectural Design Review"],
    "Material Quality Control": ["Architectural Design Review"],
    "Materials Selection": ["Architectural Design Review"],

    # Specialized Design
    "Fashion Design": ["Design"],
    "Packaging Design": ["Design"],
    "Logo Design": ["Branding Design"],
    "Typography": ["Graphic Design"],
    "Layout Design": ["Graphic Design"],
    "Infographics": ["Graphic Design"],
    "Posters": ["Graphic Design"],
    "Social Media Posts": ["Graphic Design"],
    "Visual Storytelling": ["Graphic Design"],
    "Website Editing": ["Web Application Design"],
    "Web Application Design": ["UI Design"],

    # Methods / Frameworks
    "Design Thinking": ["Design"],
    "Human-Centered Design": ["Design Thinking"],
    "User-Centered Design": ["Design Thinking"],
    "Information Architecture": ["UX Design"],
    "User Flows": ["UX Design"],
    "User Research": ["UX Design"],
    "Usability Testing": ["UX Design"],
    "Data-Driven Design": ["UX Design"],
}

Engineering_skills = {
    # Core Engineering & Design
    "Engineering": [],
    "2D Design": ["Engineering"],
    "3D Design": ["Engineering"],
    "Product Design": ["Engineering"],
    "Product Development": ["Product Design"],
    "Automotive Design": ["Product Design"],
    "Process Design": ["Engineering"],
    "Process Engineering Calculation": ["Process Design"],
    "Process Simulation": ["Process Design"],
    "Process Control Chart": ["Process Design"],
    "Process Improvement": ["Process Design"],

    # CAD & Modeling
    "CAD": ["Engineering"],
    "CAD Software": ["CAD"],
    "AutoCAD": ["CAD Software"],
    "SolidWorks": ["CAD Software"],
    "Shapr3D": ["CAD Software"],
    "CATIA": ["CAD Software"],
    "3D CAD": ["CAD"],

    # Electrical & Mechanical
    "Electrical Engineering": ["Engineering"],
    "Analog Circuit Design": ["Electrical Engineering"],
    "Digital Circuit Design": ["Electrical Engineering"],
    "PCB Design": ["Electrical Engineering"],
    "Embedded Systems": ["Electrical Engineering"],
    "Mechanical Knowledge": ["Engineering"],
    "Pneumatic System": ["Mechanical Knowledge"],
    "AC Motor": ["Mechanical Knowledge"],
    "Servo": ["Mechanical Knowledge"],
    "Wire Harness Design": ["Electrical Engineering"],

    # Industrial / Manufacturing
    "Assembly": ["Engineering"],
    "Machine Specification": ["Engineering"],
    "Laser Welding": ["Engineering"],
    "Nutrunner": ["Engineering"],
    "Robot": ["Automation Knowledge"],
    "PLC": ["Automation Knowledge"],
    "Automation Knowledge": ["Engineering"],
    "Vision Sensor": ["Automation Knowledge"],
    "Dispensing Systems": ["Automation Knowledge"],

    # Methodologies / Standards
    "FMEA": ["Quality Management"],
    "MSA": ["Quality Management"],
    "APQP": ["Quality Management"],
    "PPAP": ["Quality Management"],
    "Control Plans": ["Quality Management"],
    "DFM/DFA": ["Product Design"],
    "DFM Reviews": ["Product Design"],
    "GD&T": ["Engineering"],
    "Root Cause Analysis": ["Problem Solving"],
    "8D Methodology": ["Problem Solving"],
    "Problem Analysis and Solution (8D)": ["8D Methodology"],
    "Kaizen": ["Continuous Improvement"],
    "Lean Methodologies": ["Continuous Improvement"],
    "Continuous Improvement": ["Process Improvement"],
    "OEE": ["Production Control"],
    "Production Scheduling": ["Production Control"],
    "Production Control": ["Engineering"],
    "Production Launch Readiness": ["Production Control"],

    # Quality & Safety
    "Quality Control": ["Engineering"],
    "Quality Management": ["Quality Control"],
    "Quality Targets": ["Quality Management"],
    "Quality Risk Evaluation": ["Quality Management"],
    "SPC": ["Quality Control"],
    "Statistical Process Control": ["Quality Control"],
    "Statistical Analytical Tools": ["Quality Control"],
    "ISO Systems": ["Quality Management"],
    "ISO 14001": ["ISO Systems"],
    "ISO/TS 16949": ["ISO Systems"],
    "OHS": ["Safety Compliance"],
    "Safety Compliance": ["Engineering"],
    "Tetra Pak Safety Regulations": ["Safety Compliance"],

    # Tools / Platforms
    "Power BI": ["Data Analysis"],
    "Power Query": ["Data Analysis"],
    "Miro": ["Collaboration"],
    "Confluence": ["Collaboration"],
    "Jira": ["Project Management"],
    "MS Office": [],
    "Microsoft Office": ["MS Office"],
    "Photoshop": [],
    "Illustrator": [],
    "Unity": [],

    # Documentation & Reporting
    "Technical Writing": ["Engineering"],
    "Technical Analysis": ["Engineering"],
    "Technical Maintenance": ["Engineering"],
    "Documentation": ["Engineering"],
    "Reporting": ["Engineering"],
    "Structured Documentation in XML": ["Documentation"],
}

Legal_skills = {
    # Core Legal Knowledge
    "Law": [],
    "Civil Litigation": ["Law"],
    "Criminal Litigation": ["Law"],
    "Labor Law": ["Law"],
    "Commercial Law": ["Law"],
    "Corporate Law": ["Law"],
    "Intellectual Property Law": ["Law"],
    "Immigration Law": ["Law"],
    "Bankruptcy Law": ["Law"],

    # Corporate / Governance
    "Corporate Governance": ["Corporate Law"],
    "Corporate Transactions": ["Corporate Law"],
    "Corporate Secretarial": ["Corporate Governance"],
    "Corporate Secretary": ["Corporate Governance"],
    "Board of Directors Meetings": ["Corporate Governance"],
    "Shareholder Meetings": ["Corporate Governance"],
    "Corporate Disclosure": ["Corporate Governance"],

    # Legal Processes
    "Dispute Resolution": ["Law"],
    "Arbitration": ["Dispute Resolution"],
    "Mediation": ["Dispute Resolution"],
    "Labor Dispute Resolution": ["Dispute Resolution"],
    "Litigation Support": ["Litigation"],

    # Legal Documentation
    "Legal Drafting": ["Law"],
    "Contract Drafting": ["Legal Drafting"],
    "Contract Review": ["Legal Drafting"],
    "Drafting Legal Documents": ["Legal Drafting"],
    "Legal Document Review": ["Legal Drafting"],
    "Contract Negotiation": ["Legal Drafting"],
    "Contract Summarization": ["Legal Drafting"],
    "Document Preparation": ["Legal Drafting"],
    "Minute Taking": ["Legal Drafting"],
    "Reviewing Legal Documents": ["Legal Drafting"],

    # Compliance / Regulation
    "Legal Compliance": ["Law"],
    "Compliance": ["Law"],
    "Compliance Risk Assessment": ["Compliance"],
    "Compliance Testing": ["Compliance"],
    "Compliance Training": ["Compliance"],
    "Regulatory Obligations": ["Compliance"],
    "Regulatory Filings": ["Compliance"],
    "Internal Control": ["Compliance"],
    "Internal Investigations": ["Compliance"],
    "Policy Development": ["Compliance"],
    "Policy/Procedure Review": ["Compliance"],
    "Data Privacy": ["Compliance"],
    "Data Protection Compliance": ["Compliance"],
    "GDPR": ["Compliance"],
    "GDPR Compliance": ["GDPR"],
    "PDPA": ["Compliance"],
    "PDPA Compliance": ["PDPA"],
    "Sanctions Program Audit": ["Compliance"],

    # Legal Research & Analysis
    "Legal Research": ["Law"],
    "Legal Analysis": ["Law"],
    "Legal Consultation": ["Law"],
    "Legal Advisory": ["Law"],
    "Legal Strategy": ["Law"],
    "Due Diligence": ["Law"],
    "Investigations": ["Law"],
    "Root Cause Identification": ["Investigations"],

    # Specialized Legal Areas
    "Intellectual Property (IP)": ["Intellectual Property Law"],
    "Intellectual Property Right (IPR)": ["Intellectual Property Law"],
    "Patent": ["Intellectual Property Law"],
    "Trademark": ["Intellectual Property Law"],

    # Tools & Software
    "Microsoft Office": [],
    "MS Office Suite": ["Microsoft Office"],
    "Technological Proficiency (Microsoft Office Suite)": ["Microsoft Office"],
    "Computer Literacy": ["Microsoft Office"],
    "Database Management": [],
    "Research": ["Legal Research"],
    "Report Writing": ["Legal Drafting"],
}

Science_skills = {
    # Core Science & Lab
    "Laboratory Testing": [],
    "Sample Preparation": ["Laboratory Testing"],
    "Analytical Testing": ["Laboratory Testing"],
    "Raw Material Testing": ["Laboratory Testing"],
    "Plastics Chemical and Physical Property Testing": ["Laboratory Testing"],
    "Color Testing and Measuring": ["Laboratory Testing", "Color Theory"],
    "Sensory Assessment": ["Laboratory Testing"],
    "Gravimetric": ["Laboratory Testing"],
    "Wet Analysis": ["Laboratory Testing"],
    "Adhesion": ["Laboratory Testing"],
    "Synthesis": ["Laboratory Testing"],

    # Lab Equipment / Techniques
    "FTIR": ["Laboratory Testing"],
    "GC": ["Laboratory Testing"],
    "HPLC": ["Laboratory Testing"],
    "ICP": ["Laboratory Testing"],
    "XRF": ["Laboratory Testing"],
    "SEM": ["Laboratory Testing"],
    "BET": ["Laboratory Testing"],
    "GPC": ["Laboratory Testing"],

    # Standards & Compliance
    "GMP": ["Quality Assurance"],
    "HACCP": ["Quality Assurance"],
    "ISO Standards": ["Quality Assurance"],
    "ISO/IEC 17025": ["ISO Standards"],
    "Quality Assurance": ["Quality Management Systems"],
    "Quality Control": ["Quality Management Systems"],
    "Quality Analysis": ["Quality Control"],
    "QA": ["Quality Assurance"],
    "QC": ["Quality Control"],
    "Regulatory Compliance": ["Quality Assurance"],
    "Safety Protocols": ["Quality Assurance"],
    "Waste Management": ["Quality Assurance"],
    "Six Sigma": ["Process Improvement"],
    "Lean": ["Process Improvement"],

    # Research & Development
    "R&D": [],
    "R&D Collaboration": ["R&D"],
    "Product Trials": ["R&D"],
    "Product Design": ["R&D"],
    "Innovation": ["R&D"],

    # Tools (non-tech general)
    "ERP (SAP)": [],
    "SAP B1": ["ERP (SAP)"],
    "SAP-QM Module": ["ERP (SAP)"],
    "Microsoft Office": [],
    "MS Office": ["Microsoft Office"],
    "Excel (Macro, Pivot, VLOOKUP)": ["Microsoft Office"],
    "LaTeX": [],

    # Business / Management
    "Business Planning": [],
    "Market Research": [],
    "Marketing Strategy": ["Market Research"],
    "Project Coordination": ["Management"],
    "Management": [],
    "Team Management": ["Management"],
    "Reporting": ["Management"],
    "Commercial Expertise": ["Business Planning"],

    # Process & Improvement
    "Process Improvement": [],
    "Root Cause Analysis": ["Process Improvement"],
    "Corrective Action Tracking": ["Process Improvement"],
    "DFMEA": ["Process Improvement"],
    "Continuous Improvement": ["Process Improvement"],
}

Hr_skills = {
    # Core HR Functions
    "Human Resource Management": [],
    "HR Operations": ["Human Resource Management"],
    "HR Policies": ["Human Resource Management"],
    "HR Procedures": ["HR Policies"],
    "HR Compliance": ["HR Policies"],
    "Labor Law": ["HR Compliance"],
    "Compensation & Benefits": ["Human Resource Management"],
    "Payroll Management": ["Compensation & Benefits"],
    "Payroll Processing": ["Payroll Management"],
    "Social Security Fund Management": ["Payroll Management"],
    "Provident Fund Management": ["Payroll Management"],
    "Benefits Administration": ["Compensation & Benefits"],
    "Talent Acquisition": ["Human Resource Management"],
    "Recruitment": ["Talent Acquisition"],
    "Screening": ["Recruitment"],
    "Onboarding": ["Recruitment"],
    "Interview Coordination": ["Recruitment"],
    "Succession Planning": ["Human Resource Management"],
    "Performance Management": ["Human Resource Management"],
    "PMS": ["Performance Management"],
    "Retention": ["Performance Management"],
    "Employee Relations": ["Human Resource Management"],
    "Employee Engagement": ["Employee Relations"],
    "Grievance Handling": ["Employee Relations"],
    "Disciplinary Actions": ["Employee Relations"],

    # HR Development
    "Learning & Development": ["Human Resource Management"],
    "Training": ["Learning & Development"],
    "Training Coordination": ["Training"],
    "Training Management": ["Learning & Development"],
    "Training Programs": ["Training"],
    "Training Needs Identification": ["Training Management"],
    "Career Development": ["Learning & Development"],
    "Coaching": ["Learning & Development"],
    "Executive Coaching": ["Coaching"],
    "Employee Support": ["Employee Relations"],
    "People Development": ["Learning & Development"],

    # Strategic HR
    "Strategic HR": ["Human Resource Management"],
    "Workforce Planning": ["Strategic HR"],
    "Manpower Strategies": ["Workforce Planning"],
    "Mergers & Acquisitions": ["Strategic HR"],
    "Transformation Projects": ["Strategic HR"],
    "Organization Development": ["Strategic HR"],
    "Organizational Design": ["Organization Development"],
    "Talent Management": ["Strategic HR"],
    "Talent Review": ["Talent Management"],
    "Employer Branding": ["Strategic HR"],

    # HR Analytics / Systems
    "HR Analytics": ["Human Resource Management"],
    "Data-Driven HR Decision-Making": ["HR Analytics"],
    "HR Tech": ["HR Analytics"],
    "HRIS Systems": ["HR Tech"],
    "Applicant Tracking Systems": ["Recruitment"],
    "Workday (WD) System": ["HRIS Systems"],
    "Payroll Management Software": ["Payroll Management"],

    # Legal & Compliance
    "Regulation Revision": ["HR Compliance"],
    "Visa & Work Permit Handling": ["HR Compliance"],
    "Tax Management": ["HR Compliance"],
    "Tax Reporting": ["Tax Management"],

    # Collaboration & Coordination
    "Internal Communication": ["Human Resource Management"],
    "Relationship Management": ["Employee Relations"],
    "Partnership Building": ["Relationship Management"],
    "Team Collaboration": ["Human Resource Management"],

    # General / Support Skills
    "Administrative Tasks": ["Human Resource Management"],
    "Documentation Management": ["Administrative Tasks"],
    "Scheduling": ["Administrative Tasks"],
    "Report Preparation": ["Administrative Tasks"],
    "Reporting": ["Report Preparation"],
    "Housekeeping Supervision": ["Administrative Tasks"],
}

Soft_skills = {
    # Communication / Thinking
    "Communication Skills": [],
    "Analytical Skills": [],
    "Logical Thinking": ["Analytical Skills"],
    "Problem Solving": ["Analytical Skills", "Logical Thinking"],
    "Presentation Skills": ["Communication Skills"],
    "Interpersonal Skills": ["Communication Skills"],
    "Consulting": ["Communication Skills", "Presentation Skills", "Problem Solving"],
    "Negotiation": ["Communication Skills"],

    # Leadership / Team
    "Teamwork": [],
    "Team Leadership": ["Teamwork"],
    "People Management": ["Team Leadership"],
    "Stakeholder Management": ["Team Leadership"],
    "Hiring": ["Team Leadership"],
    "Roadmapping": ["Team Leadership"],
    "Evaluation": ["Team Leadership"],
    "Experimentation": ["Team Leadership"],
    "Team Management": ["Leadership", "Collaboration", "Coordination"],
    "Leadership": ["Communication Skills"],
    "Management": ["Leadership", "Planning"],
    "Team Development": ["Team Management"],
    "Coaching": ["Team Management"],

    # Organization / Planning
    "Planning": [],
    "Prioritization": ["Planning"],
    "Time Management": ["Planning", "Prioritization"],
    "Strategic Thinking": ["Planning", "Analytical Skills"],
    "Change Management": ["Planning", "Communication Skills", "Leadership"],
    "Organizational Skills": ["Planning"],
    "Multitasking": ["Time Management"],
    "Detail-Oriented": ["Attention to Detail"],
    "Attention to Detail": [],

    # Process / Business
    "Business Process Knowledge": ["Process Analysis"],
    "Product Strategy": ["Planning", "Strategic Thinking", "Business Process Knowledge"],
    "Process Analysis": ["Analytical Skills"],
    "Process Improvement": ["Process Analysis", "Analytical Skills"],
    "Decision Making": ["Analytical Skills"],
    "Systematic Thinking": ["Analytical Skills"],
    "Creative Thinking": [],
    "Proactive Mindset": [],
    "Quick Learning": [],
    "Independent Working": [],
    "Cultural Awareness": [],

    # Collaboration / Coordination
    "Collaboration": ["Communication Skills"],
    "Coordination": ["Collaboration"],
    "Training": ["Communication Skills", "Presentation Skills"],
    "Cross-Functional Collaboration": ["Collaboration"],

    # Personal Values
    "Respect": [],
    "Responsibility": [],

    "Creativity": [],
    "Creative Thinking": ["Creativity"],
    "Analytical Thinking": ["Analytical Skills"],
    "Adaptable": [],
    "Brand Consistency": ["Attention to Detail"],
    "Attention to Detail": [],
    "Detail-Oriented": ["Attention to Detail"],
    "Persuasion": ["Communication Skills"],
    "Visual Communication": ["Communication Skills"],
    "Storytelling": ["Communication Skills"],
    "Presentation": ["Communication Skills"],
    "Presentation Skills": ["Communication Skills"],
    "Market Research": ["Analytical Skills"],
    "Innovation": ["Creativity"],
    "Collaboration": ["Communication Skills"],
    "Coordination": ["Collaboration"],
    "Team Management": ["Leadership", "Collaboration"],
    "Organizational Skills": ["Planning"],
    "Multitasking": ["Time Management"],
    "Problem-Solving": ["Analytical Skills", "Logical Thinking"],
    "Planning Skills": ["Planning"],

    "Analytical Mindset": ["Analytical Skills"],
    "Analytical Thinking": ["Analytical Skills"],
    "Attention to Detail": [],
    "Detail-Oriented": ["Attention to Detail"],
    "Conceptual Skill": [],
    "Decision-Making": ["Problem Solving"],
    "Investigative Principles": ["Analytical Skills"],
    "Learning": [],
    "Observation": [],
    "Proactive Mindset": [],
    "Flexible": [],
    "Efficient Operation": ["Time Management"],
    "Reliable Operation": ["Responsibility"],
    "Goal-Oriented": ["Strategic Thinking"],
    "Supervision Skill": ["Leadership"],
    "Team Building": ["Teamwork"],
    "Multinational Teams": ["Collaboration"],
    "Multi-Task Management": ["Time Management"],

    "Analytical Skills": [],
    "Attention to Detail": [],
    "Detail-Oriented": ["Attention to Detail"],
    "Business Communication Skills": ["Communication Skills"],
    "Communication Skills": [],
    "Written Communication": ["Communication Skills"],
    "Verbal Communication": ["Communication Skills"],
    "Presentation": ["Communication Skills"],
    "Negotiation": ["Communication Skills"],
    "Coordination Skills": ["Collaboration"],
    "Cross-Functional Collaboration": ["Collaboration"],
    "Intercultural Skills": ["Collaboration"],
    "Relationship Building": ["Collaboration"],
    "Interpersonal Skills": ["Communication Skills"],
    "Independent Thinking": [],
    "Independent Work": [],
    "Confidentiality": [],
    "Integrity": [],
    "Service Mindset": [],
    "Reliable": [],
    "Adaptability": [],
    "Stress Tolerance": [],
    "Working Under Pressure": ["Stress Tolerance"],
    "Problem-Solving": ["Analytical Skills", "Logical Thinking"],
    "Decision-Making": ["Problem-Solving"],
    "Can-Do Attitude": ["Adaptability"],
    "Time Management": [],
    "Time Keeping": ["Time Management"],
    "Multi-Tasking": ["Time Management"],
    "Organization": [],
    "Organizational Skills": ["Organization"],
    "Office Management": ["Organization"],
    "Training": [],

    "Analytical Skills": [],
    "Analytical Thinking": ["Analytical Skills"],
    "Attention to Detail": [],
    "Observation": [],
    "Communication Skills": [],
    "Collaboration": ["Communication Skills"],
    "Leadership": ["Communication Skills"],
    "Time Management": [],
    "Written Communication": ["Communication Skills"],
    "Verbal Communication": ["Communication Skills"],
    "Innovative Thinking": ["Analytical Skills"],
    "Learning Ability": [],
}

DATA_SKILL = [Tech_skills,Accounting_finance_skills,Design_skills,Engineering_skills,Legal_skills,Science_skills,Hr_skills]